// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Workshop SpriteKit",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Workshop SpriteKit",
            targets: ["AppModule"],
            bundleIdentifier: "mooncat.How-make-a-game-in-Sprite-kit",
            teamIdentifier: "K4H4UFJU24",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .moon),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)